default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: file_vault_development

test:
  <<: *default
  database: file_vault_test

production:
  <<: *default
  database: file_vault_production
